### ISSUE TITLE
IndexOutOfBoundsException when generating permutation for empty list

### ISSUE THREAD

**Issue by nstdio** [dpaukov/combinatoricslib3#19]
```java
@Test
public void test_zero_permutation_of_empty_with_repetition() {
  List<List<Object>> permutations = Generator.permutation(Collections.emptyList())
      .withRepetitions(0)
      .stream()
      .collect(toList());

  assertThat(permutations).isEmpty();
}
```
Expected: test should ✓
Actual: `java.lang.IndexOutOfBoundsException`
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	<3 internal lines>
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.paukov.combinatorics3.PermutationWithRepetitionIterator.<init>(PermutationWithRepetitionIterator.java:24)
	at org.paukov.combinatorics3.PermutationWithRepetitionGenerator.iterator(PermutationWithRepetitionGenerator.java:29)
	at org.paukov.combinatorics3.PermutationWithRepetitionGenerator.stream(PermutationWithRepetitionGenerator.java:34)
	at org.paukov.combinatorics3.PermutationsWithRepetitionsTest.test_zero_permutation_of_empty_with_repetition(PermutationsWithRepetitionsTest.java:89)
```

**Comment by dpaukov** [comment]
The change is available in version 3.3.3.
